title: Matheus's Blog
author: Matheus Silva
subtitle: Opinions are my own

url: "https://matheussilvasantos.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/matheussilvasantos"
footer_text: ""

profile-picture:
favicon_location:

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css
